spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:pokedex-mysqldb}:3306/pokedex
    username: pokedex
    password: pokedex
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true